### PR TITLE
Use screeps library

### PR DESCRIPTION
**Pull request by TooAngel**
Introducing the screeps library from pypi. Using the same library for all
projects will minimize the duplicate code and will improve and complete
the library itself.

### CODE REVIEW

**Comment by tedivm** [comment]
We are using the same library in all the projects, the [python-screeps](https://github.com/tedivm/python-screeps) library. I just haven't uploaded it to PyPi yet so I'm pulling it in via git.

I do plan on moving the websocket stuff to this library.

**Comment by TooAngel** [comment]
I released my library to pypi (https://pypi.python.org/pypi/screeps), some parts which I saw in your code were pretty familiar.
Websocket is included but not yet all the REST methods.
Maybe we should join forces here before maintaining multiple libraries, as you like.

You can close the PR if you prefer to keep your library.

**Comment by tedivm** [comment]
My version is the one that the community has been working on, based on the [gist dhzu](https://gist.github.com/dzhu/d6999d126d0182973b5c) put together. It's also got support for a lot more functionality than yours currently does, so I'd recommending starting with it as the basis.

**Comment by TooAngel** [comment]
K, as you prefer, so I will close this one.

**Pull request closed without merging**
